package com.oopbasics.assignments;

public class Assignment0508 {

    // DECLARE A CLASS PRODUCT
    // DECLARE A CLASS CUSTOMER
    // DECLARE A CLASS SUPERMART
    // DECLARE A CLASS BILL
    // CUSTOMER -> HAS A BILL
    // SUPERMART -> HAS A CUSTOMER
    // SUPERMART -> HAS A PRODUCT
    // DECLARE UTILITY CLASS BILLINGUTILS
    // CALCULATE TOTALBILL OF A CUSTOMER BASED ON PRODUCTS PURCHASED
    // CALCULATE APPLICABLE DISCOUNTS (Decide own slab)

}
